# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
dist: xenial

r_binary_packages:
  - devtools
  - roxygen2

after_success:
  - Rscript -e 'devtools::install();devtools::test()'